GetAllPreRegApplications:
   Prereg_GetAllPreRegApplications_All_Valid_Smoke_sid:
      endPoint: /preregistration/v1/applications
      description: Retrieve all preregistered applications with a valid preregistration ID
      role: batch
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: preReg/GetAllPreRegApplications/getAllPreRegApplications
      outputTemplate: preReg/GetAllPreRegApplications/GetAllPreRegApplicationsResult
      input: '{}'
      output: '{
  "bookingType": "NEW_PREREGISTRATION"
}'
   Prereg_GetAllPreRegApplications_LOST_UIN_APPLICATION_sid:
      endPoint: /preregistration/v1/applications
      description: Retrieve all preregistered applications with a preregistration ID associated with the lost UIN application
      role: batch
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: preReg/GetAllPreRegApplications/getAllPreRegApplications
      outputTemplate: preReg/GetAllPreRegApplications/GetAllPreRegApplicationsResult
      input: '{}'
      output: '{
  "bookingType": "NEW_PREREGISTRATION"
}'
   Prereg_GetAllPreRegApplications_DELETE_UIN_APPLICATION_sid:
      endPoint: /preregistration/v1/applications
      description: Retrieve all preregistered applications with a preregistration ID associated with a deleted UIN application
      role: batch
      checkErrorsOnlyInResponse: true
      restMethod: get
      inputTemplate: preReg/GetAllPreRegApplications/getAllPreRegApplications
      outputTemplate: preReg/GetAllPreRegApplications/GetAllPreRegApplicationsResult
      input: '{}'
      output: '{
  "bookingType": "NEW_PREREGISTRATION"
}'