apiVersion: v2
name: prereg-captcha
description: A Helm chart for MOSIP Pre-registration Captcha Service
type: application
version: 1.3.0-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - prereg-captcha
  - prereg
maintainers:
  - email: info@mosip.io
    name: MOSIP
