apiVersion: v2
name: prereg-datasync
description: A Helm chart for MOSIP Pre-registration Datasync service
type: application
version: 1.3.0-beta.1-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - prereg-datasync
maintainers:
  - email: info@mosip.io
    name: MOSIP
