apiVersion: v2
name: prereg-booking
description: A Helm chart for MOSIP Pre-registration application service
type: application
version: 12.0.3-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - prereg-booking
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
